"""empty message

Revision ID: 30e808c6f9d0
Revises: 
Create Date: 2019-11-08 17:16:50.085566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30e808c6f9d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobid.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('jobid')
    # ### end Alembic commands ###
