"""empty message

Revision ID: 42399cfbdac3
Revises: d70fa565f4f8
Create Date: 2019-11-08 17:38:11.745521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42399cfbdac3'
down_revision = 'd70fa565f4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobid.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
